close tags by default
tidalmigrations/swagger-ui pull request #1
Opened 2018-05-01 20:31 UTC by shrutimistry

### Description

- added doc expansion to close tags
- added filter to search for tags
- sorted tags in alphabetical order

### How Has This Been Tested?
its not

2018-05-02 21:10 UTC, prees1 requested changes
Looks like there are some changes to favicon files in this PR? `dist/tidal_icon.png`, `src/img/favicon-32x32.png`, src/plugins/topbar/favicon-32x32.png`. But don't see it mentioned in the description.

Also, great PR description! :)

2018-05-02 21:10 UTC, prees1 commented on src/core/index.js
> -      "patch",
Was this intentional? I don't see it in the (amazing!) description in the pull request.

2018-05-03 17:18 UTC, shrutimistry commented on src/core/index.js
> -      "patch",
yea since we don't use patch

2018-05-03 21:01 UTC, prees1 approved these changes
Great!

2018-05-04 13:55 UTC, merged